apiVersion: v1
kind: ConfigMap
metadata:
  name: short-url-config
  namespace: short-url
data:
  REDIS_HOST: "redis-master"
  REDIS_PORT: "6379"
  REDIS_SENTINEL_HOSTS: "redis-sentinel-0.redis-sentinel:26379,redis-sentinel-1.redis-sentinel:26379,redis-sentinel-2.redis-sentinel:26379"
  REDIS_MASTER_NAME: "mymaster"
  CASSANDRA_HOST: "cassandra-0.cassandra.short-url.svc.cluster.local"
  CASSANDRA_PORT: "9042"
  CASSANDRA_CLUSTER_NAME: "short-url-cluster"
  CASSANDRA_DC: "dc1"
  CASSANDRA_KEYSPACE: "short_url"
  URL: "http://short-url.local"
