apiVersion: v1
kind: Secret
metadata:
  name: short-url-secret
  namespace: short-url
type: Opaque
stringData:
  # Change these values in production
  REDIS_PASSWORD: ""  # Empty - no password configured on Redis
  SALT: "my_secret_salt"
